namespace BioFSharp.ArcIR

/// Severity shared by diagnostics from F1, curation, validation, and F2.
[<RequireQualifiedAccess>]
type DiagnosticSeverity =
    /// Informational finding that requires no corrective action.
    | Info
    /// Finding that preserves a usable result but may require review.
    | Warning
    /// Finding that prevented the requested result from being produced safely.
    | Error

/// One immutable diagnostic occurrence emitted beside, rather than inside, an ArcIR state.
type Diagnostic =
    {
        /// Stable identity of this diagnostic occurrence.
        Id: Iri
        /// Stable machine-readable diagnostic category.
        Code: Iri
        /// Importance of the finding.
        Severity: DiagnosticSeverity
        /// Human-readable explanation.
        Message: string
        /// Artifact-qualified fragments directly affected by the finding.
        Targets: FragmentRef list
        /// Additional artifact-qualified fragments that help explain the finding.
        Related: FragmentRef list
    }

/// An immutable collection of diagnostics generated by one process.
type DiagnosticReport =
    {
        /// Stable identity of the report.
        Id: Iri
        /// Diagnostics keyed by their authoritative identities.
        Diagnostics: Map<Iri, Diagnostic>
    }

/// Construction helpers for immutable diagnostic reports.
[<RequireQualifiedAccess>]
module DiagnosticReport =

    /// Creates a report and rejects duplicate diagnostic identities.
    let create id (diagnostics: Diagnostic seq) =
        let values =
            ((Map.empty, Set.empty), diagnostics)
            ||> Seq.fold (fun (result, seen) diagnostic ->
                if Set.contains diagnostic.Id seen then
                    invalidArg (nameof diagnostics) (sprintf "Duplicate diagnostic identity: %s" diagnostic.Id.Value)

                Map.add diagnostic.Id diagnostic result, Set.add diagnostic.Id seen)
            |> fst

        { Id = id; Diagnostics = values }

    /// Creates an empty report with the supplied stable identity.
    let empty id = create id Seq.empty
